baseURL = 'https://dora.dev/'
languageCode = 'en-us'
theme = 'dora-2025'
rssLimit = 10
ignoreFiles = "README.md"

[taxonomies]
  tag = "tags"

[permalinks]
  tags = "/insights/tags/:slug/"

[markup]
    [markup.highlight]
        noClasses = false

    [markup.goldmark.renderer]
        unsafe= true

[params]
    Keywords = "DevOps, Lead time, Deploy frequency, Change fail rate, MTTR, Time to restore, metrics, DORA"
    Description = "DORA is a long running research program that seeks to understand the capabilities that drive software delivery and operations performance. DORA helps teams apply those capabilities, leading to better organizational performance."
    DefaultSocialImage = "/img/misc/dora_social_image.png"

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5

[[cascade]]
  [cascade._target]
    path = "**/docs"
  [cascade._build]
    render = "never"
    list = "never"
